career_skills = {
    "Data Scientist": ["python", "ml", "statistics", "sql"],
    "Frontend Developer": ["html", "css", "javascript", "react"],
    "Backend Developer": ["python", "django", "api", "sql"],
    "Software Engineer": ["java", "oop", "git", "sql"],
    "Cyber Security Analyst": ["networking", "security", "linux"],
    "Financial Analyst": ["excel", "financial modeling", "accounting", "sql"],
    "Investment Analyst": ["equity research", "valuation", "excel"],
    "Risk Analyst": ["statistics", "probability", "excel", "sql"],
    "FinTech Engineer": ["python", "sql", "data analysis", "financial systems"],
    "Accountant": ["accounting", "taxation", "excel"],
    "Marketing Specialist": ["marketing", "seo", "content creation"],
    "Graphic Designer": ["graphic design", "photoshop", "creativity"],
    "Nurse": ["nursing", "patient care", "communication"],
    "Project Manager": ["project management", "planning", "leadership"],
    "UX Designer": ["ux design", "figma", "user research", "wireframing"],
    "UX/UI Designer": ["ux design", "ui design", "figma", "prototyping"],
    "DevOps Engineer": ["docker", "kubernetes", "ci/cd", "linux", "jenkins"],
    "Product Manager": ["product strategy", "roadmapping", "analytics", "user stories", "agile"],
    "Data Analyst": ["sql", "excel", "tableau", "data visualization", "power bi"],
    "iOS Developer": ["swift", "ios", "mobile development", "xcode"],
    "Android Developer": ["kotlin", "android", "mobile development", "java"],
    "Mobile Developer": ["react native", "javascript", "mobile development", "flutter"],
    "Cloud Architect": ["aws", "cloud architecture", "azure", "gcp", "terraform"],
    "Cloud Solutions Architect": ["terraform", "aws", "cloud architecture", "networking"],
    "Business Analyst": ["business analysis", "requirements gathering", "sql", "documentation"],
    "Digital Marketing Manager": ["seo", "google analytics", "content marketing", "social media"],
    "Digital Marketing Specialist": ["email marketing", "seo", "content marketing", "paid advertising"],
    "Content Creator": ["content writing", "video editing", "storytelling", "content creation"],
    "Content Writer": ["content creation", "video editing", "storytelling", "seo"],
    "Content Producer": ["podcasting", "content creation", "storytelling"],
    "HR Manager": ["recruitment", "hr management", "communication", "employee relations"],
    "HR Specialist": ["communication", "recruitment", "hr management"],
    "Talent Acquisition Manager": ["talent acquisition", "recruitment", "hr management"],
    "Sales Manager": ["sales", "negotiation", "crm", "customer relations"],
    "Sales Executive": ["customer relations", "sales", "communication"],
    "Business Development Manager": ["business development", "sales", "negotiation"],
    "Teacher": ["curriculum development", "lesson planning", "communication"],
    "Education Specialist": ["lesson planning", "student assessment", "curriculum development"],
    "Educator": ["student assessment", "curriculum development", "communication"],
    "High School Teacher": ["classroom management", "lesson planning", "communication"],
    "College Professor": ["teaching", "curriculum development", "student assessment"],
    "Healthcare Professional": ["patient care", "medical knowledge", "empathy"],
    "Medical Professional": ["medical knowledge", "patient care", "communication"],
    "Doctor": ["diagnosis", "patient care", "medical knowledge"],
    "Psychologist": ["empathy", "counseling", "communication"],
    "Therapist": ["counseling", "therapy", "empathy"],
    "Lawyer": ["legal research", "contract law", "writing"],
    "Attorney": ["contract law", "legal research", "negotiation"],
    "Legal Counsel": ["legal writing", "legal research", "contract law"],
    "Trial Lawyer": ["litigation", "legal research", "contract law"],
    "Compliance Officer": ["compliance", "legal research", "contract law"],
    "Ethical Hacker": ["ethical hacking", "penetration testing", "security"],
    "Penetration Tester": ["penetration testing", "networking", "security"],
    "Security Researcher": ["security", "ethical hacking", "linux"],
    "Security Analyst": ["vulnerability assessment", "security", "networking"],
    "Security Engineer": ["incident response", "security", "networking"],
    "Blockchain Developer": ["blockchain", "solidity", "cryptography"],
    "Smart Contract Developer": ["solidity", "smart contracts", "blockchain"],
    "Blockchain Engineer": ["cryptography", "blockchain", "security"],
    "Web3 Developer": ["web3", "blockchain", "solidity"],
    "NFT Developer": ["nft", "blockchain", "solidity"],
    "Game Developer": ["game design", "unity", "c#"],
    "Game Designer": ["unity", "c#", "game design"],
    "Game Engineer": ["unreal engine", "c++", "game design"],
    "Video Game Designer": ["game design", "unity", "3d modeling"],
    "Game Programmer": ["c#", "unity", "game programming"],
    "Photographer": ["photography", "photo editing", "creativity"],
    "Professional Photographer": ["photo editing", "lightroom", "photography"],
    "Videographer": ["videography", "video editing", "storytelling"],
    "Video Editor": ["video editing", "premiere pro", "storytelling"],
    "Film Director": ["filmmaking", "videography", "storytelling"]
}

def skill_gap(user_skills, career):
    user = set([s.strip().lower() for s in user_skills.split(",")])
    required = set([s.lower() for s in career_skills.get(career, [])])
    missing = required - user
    return list(missing)

def get_required_skills(career):
    """Get total required skills for a career"""
    return career_skills.get(career, [])
